config/routes.rb
Postit::Application.routes.draw do
  resources :posts, :except => :destroy do
  	resources :comments, :except => :destroy
  end

  resources :categories

  resources :users

  resources :sessions

  match '/login' => 'sessions#new'
  match '/logout' => 'sessions#destroy'
  match '/register' => 'users#new'
  match '/posts/:id/up' => 'posts#upvote'
  match '/posts/:id/down' => 'posts#downvote'
  match '/comments/:id/up' => 'comments#upvote'
  match '/comments/:id/down' => 'comments#downvote'

  root to: 'posts#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :post_has_categories
	has_many :posts, :through => :post_has_categories
end

app/models/comments.rb
class Comments < ActiveRecord::Base
	belongs_to :post
	belongs_to :user

	validates_presence_of :content
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :post_has_categories
	has_many :categories, :through => :post_has_categories
	has_many :comments, :dependent => :destroy
	has_many :votes, as: :voteable
	accepts_nested_attributes_for :comments
	accepts_nested_attributes_for :categories
	accepts_nested_attributes_for :post_has_categories
	validates_presence_of :title, :description

	def post_score
		score = 0
		score += self.votes.where(vote: 1).size - self.votes.where(vote: -1).size
		return score
	end
end

app/models/post_has_category.rb
class PostHasCategory < ActiveRecord::Base
  belongs_to :category
  belongs_to :post
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	validates_presence_of :username, :password
	validates_presence_of :password_confirmation
	validates_uniqueness_of :username

	attr_accessible :username, :name, :password, :password_confirmation

	has_many :posts
	has_many :comments
	has_many :votes

	def self.authenticate(username, password)
		find_by_username(username).try(:authenticate, password)
	end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  attr_accessible :post_id, :user_id, :vote

  belongs_to :user
  belongs_to :voteable, polymorphic: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def is_logged_in?
  	if current_user
  		return true
  	end
  	return false
  end

  def check_login
  	unless is_logged_in?
  		redirect_to '/login', :alert => "You need to log in to do that."
  	end
  end

  helper_method :current_user
  helper_method :is_logged_in?
  helper_method :check_login
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def index
		@categories = Category.all
	end

	def new
		check_login
		@category = Category.new
	end

	def show
		@category = Category.find(params[:id])
	end

	def create
		@category = Category.new(params[:category])

		if @category.save
			redirect_to(categories_path, :notice => "Your category was created successfully.")
		else
			render :action => 'new'
		end
	end

	def edit
		check_login
		@category = Category.find(params[:id])
	end

	def update
		@category = Category.find(params[:id])

		if @category.update_attributes(params[:category])
			redirect_to(categories_path, :notice => "Your category was updated successfully.")
		else
			render :action => 'edit'
		end
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def show

	end

	def new

	end

	def create
		@comment = Comments.new(:user_id => params['comments'][:user_id], :title => params['comments'][:title], :content => params['comments'][:content], :post_id => params['comments'][:post_id])
		@post = Post.find(params[:post_id])
		if @comment.save
			redirect_to(@post, :notice => "Your comment was posted successfully.")
		else
			redirect_to(@post, :error => "There was an error posting your comment.")
		end
	end

	def destroy

	end

	def edit
		@comment = Comments.find(param[:id])
	end

	def upvote

	end

	def downvote

	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  	@posts = Post.order("created_at DESC").all
  end

  def new
    check_login
    @post = Post.new
    @category_list = Category.all
  end

  def create
    params[:post][:categories].delete("")
    params[:post][:categories].map! {|category| Category.find(category)}
  	@post = Post.new(params[:post])
  	if @post.save
  		redirect_to(@post, :notice => "Your post was created successfully.")
  	else
  		render :action => "new"
  	end
  end

  def edit
    check_login
  	@post = Post.find(params[:id])
    unless @post.user_id == current_user.id
      redirect_to @post, :error => "You're not the owner of this post."
    end
    @category_list = Category.all
  end

  def update
  	@post = Post.find(params[:id])
    params[:post][:categories].delete("")
    params[:post][:categories].map! {|category| Category.find(category)}
  	if @post.update_attributes(params[:post])
  		redirect_to(@post, :notice => "Your post was updated successfully.")
  	else
  		render :action => "edit"
  	end
  end

  def show
  	@post = Post.find(params[:id])
  	@comments = Comments.find_all_by_post_id(params[:id])
  	@comment = Comments.new
  end

  def upvote
    check_login
    @post = Post.find(params[:id])
    @post.votes << Vote.new(:user_id => session[:user], :vote => 1)
    respond_to do |format|
      format.js
    end
  end

  def downvote
    check_login
    @post = Post.find(params[:id])
    @post.votes << Vote.new(:user_id => session[:user], :vote => -1)
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new

	end

	def create
		@user = User.find_by_username(params[:username])
		if @user.authenticate(params[:password])
			session[:user_id] = @user.id
			redirect_to root_url, :notice => "Welcome, #{@user.name}."
		else
			flash.now.alert "Your email or password was incorrect."
			render "new"
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to root_url, :notice => "You have been logged out."
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.new(params[:user])

		if @user.save!
			session[:user_id] = @user.id
			redirect_to posts_path, :notice => "Welcome, #{@user.name}."
		else
			flash.now.alert "There was an error creating your account."
			render :new
		end
	end

	def edit
		check_login
		@user = User.find(session[:user_id])
		unless @user.id == current_user.id
			redirect_to user_path(@user)
		end
	end

	def update
		@user = User.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/edit.html.erb
<h2>Edit Category "<%= @category.name %>"</h2>

<%= form_for @category, :url => category_path(@category.id) do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<br />
	<%= f.submit :value => "Update" %>
<% end %>

app/views/categories/index.html.erb
<h2>List of Categories</h2>

<table>
	<tr>
		<th>Category Name</th>
		<th>Posts</th>
		<th></th>
	</tr>
	<% @categories.each do |category| %>
	<tr>
		<td><a href="<%= category_path(category.id) %>"><%= category.name %></a></td>
		<td><%= category.posts.length %></td>
		<td><a href="<%= edit_category_path(category.id) %>">Edit</a></td>
	</tr>
	<% end %>
</table>

app/views/categories/new.html.erb
<h2>New Category</h2>

<%= form_for @category, :url => categories_path do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<br />
	<%= f.submit :value => "Create" %>
<% end %>

app/views/categories/show.html.erb
<h2>Posts for Category "<%= @category.name %>"</h2>

<% @category.posts.each do |post| %>
	<div class="post-item">
		<h3><a href="<% unless post.url.empty? %><%= post.url %><% else %><%= post_path(post.id) %><% end %>" rel="external"><%= post.title %></a></h3>
		<%= post.description %>
		<div class="metadata">
			Posted by <%= post.user.name %>
			<% if post.categories.length > 0 %> in 
				<% post.categories.each_with_index do |category,i| %>
					<a href="<%= category_path(category.id) %>"><%= category.name %></a><% unless i == post.categories.length - 1 %>, <% end %>
				<% end %>
			<% end %>
		</div>
	</div>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= [:notice, :success].include?(name) ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<h1><a href="<%= root_url %>">Post It!</a></h1>
<ul class="nav">
  <% if current_user.nil? %>
	<li><a href="/login">Log in</a></li>
	<li><a href="/register">Register</a></li>
  <% else %>
	<li><%= link_to "New Post", new_post_path %></li>
	<li><%= link_to "Manage Categories", categories_path %></li>
	<li><%= link_to "Edit Account", edit_user_path(session[:user_id]) %></li>
	<li><a href="/logout">Log out</a></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tealeaf Academy - Postit</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <link href='http://fonts.googleapis.com/css?family=Roboto+Slab:400,700|Roboto:400,400italic,700,700italic' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="page">
      <header>
        <div class="navbar">
          <%= render 'layouts/navigation' %>
        </div>
      </header>
      <div id="main" role="main">
        <%= render 'layouts/messages' %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/posts/_voting.html.erb
Score: <span class="score post-<%= post.id %>-score"><%= post.post_score %></span><% if is_logged_in? %> (<a href="/posts/<%= post.id %>/up" class="upvote">+</a> / <a href="/posts/<%= post.id %>/down" class="downvote">-</a>)<% end %>

app/views/posts/downvote.js.erb
$('.post-<%= @post.id %>-score').html(<%= @post.post_score %>);

app/views/posts/edit.html.erb
<h2>Edit Post</h2>

<%= form_for @post, :url => post_path(@post.id) do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %>
	<%= f.label :url, "URL" %>
	<%= f.text_field :url %>
	<%= f.label :description %>
	<%= f.text_area :description %>
	<%= f.label :categories %>
	<%= f.select :categories, @category_list.collect{|c| [c.name, c.id]}, {}, {multiple: 'multiple'} %>
	<br />
	<%= f.submit %>
<% end %>

app/views/posts/index.html.erb
<h2>All Posts</h2>
<% @posts.each do |post| %>
	<div class="post-item">
		<h3><a href="<% unless post.url.empty? %><%= post.url %><% else %><%= post_path(post.id) %><% end %>" rel="external"><%= post.title %><% unless post.url.empty? %>&rarr;<% end %></a></h3>
		<div class="voting">
			<%= render :partial => 'voting', :locals => {:post => post} %>
		</div>
		<div class="post-content">
			<%= post.description %>
		</div>
		<div class="metadata">
			<a href="<%= post_path(post.id) %>">∞</a> Posted by <%= post.user.name %> <%= time_ago_in_words(post.created_at) %> ago
			<% if post.categories.length > 0 %> in 
				<% post.categories.each_with_index do |category,i| %>
					<a href="<%= category_path(category.id) %>"><%= category.name %></a><% unless i == post.categories.length - 1 %>, <% end %>
				<% end %>
			<% end %>
			<% if post.user.id == session[:user_id] %>
				| <a href="<%= edit_post_path(post.id) %>">Edit</a>
			<% end %>
		</div>
	</div>
<% end %>

app/views/posts/new.html.erb
<h2>Create Post</h2>

<%= form_for @post, :url => posts_path do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %>
	<%= f.label :url, "URL" %>
	<%= f.text_field :url %>
	<%= f.label :description %>
	<%= f.text_area :description %>
	<%= f.hidden_field :user_id, :value => session[:user_id] %>
	<%= f.label :categories %>
	<%= f.select :categories, @category_list.collect{|c| [c.name, c.id]}, {}, {multiple: 'multiple'} %>
	<br />
	<%= f.submit :value => "Post" %>
<% end %>

app/views/posts/show.html.erb
<div class="post-item show" data-id="<%= @post.id %>">
	<h2><% unless @post.url.empty? %><a href="<%= @post.url %>" rel="external"><% end %><%= @post.title %><% unless @post.url.empty? %>&rarr;</a><% end %></h2>
	<div class="voting">
		<%= render :partial => 'voting', :locals => {:post => @post} %>
	</div>

	<div class="post-content">
	<%= @post.description %>
	</div>

	<div class="metadata">
		Posted by <%= @post.user.name %> <%= time_ago_in_words(@post.created_at) %> ago
			<% if @post.categories.length > 0 %> in 
				<% @post.categories.each_with_index do |category,i| %>
					<a href="<%= category_path(category.id) %>"><%= category.name %></a><% unless i == @post.categories.length - 1 %>, <% end %>
				<% end %>
			<% end %>
			<% if @post.user.id == session[:user_id] %>
				| <a href="<%= edit_post_path(@post.id) %>">Edit</a>
			<% end %>
	</div>

	<div id="comments">
		<div id="comment-form">
			<h3>Post a Comment</h3>
			<%= form_for [@post, @comment], :url => post_comments_path(@post) do |f| %>
				<%= f.label :title %>
				<%= f.text_field :title %>
				<%= f.label :content %>
				<%= f.text_area :content, :rows => 10 %>
				<%= f.hidden_field :user_id, :value => 1 %>
				<br />
				<%= f.submit :value => "Post" %>
			<% end %>
		</div>
		<% @comments.each do |comment| %>
			<div class="comment-item">
				<h4><%= comment.title %></h4>
				<div class="comment-body">
					<%= comment.content %>
				</div>
				<div class="comment-meta">
					Posted by <%= comment.user.name %>
				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/posts/upvote.js.erb
$('.post-<%= @post.id %>-score').html(<%= @post.post_score %>);

app/views/users/edit.html.erb
<h2>Edit Account</h2>

<%= form_for @user, :url => user_path(@user.id) do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.label :password %>
	<%= f.password_field :password %>
	<%= f.label :password_confirmation %>
	<%= f.password_field :password_confirmation %>
	<br />
	<%= f.submit :value => "Update" %>
<% end %>

app/views/users/new.html.erb
<h2>Register</h2>

<%= form_for @user, :url => users_path do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.label :username %>
	<%= f.text_field :username %>
	<%= f.label :password %>
	<%= f.password_field :password %>
	<%= f.label :password_confirmation %>
	<%= f.password_field :password_confirmation %>
	<br />
	<%= f.submit :value => "Register" %>
<% end %>